[package]
name = "soccer_table"
description = "compute soccer tables from plain text match results"
license = "MIT"
version = "0.1.0"
edition = "2021"

[dependencies]
regex = "1.10.4"

[[bin]]
name = "soccer-table"
path = "src/main.rs"
