[package]
name = "ex_51_pushing_notes_to_firebase"
version = "0.1.0"
edition = "2021"

[dependencies]
akshually = "0.2.3"
chrono = "0.4.38"
dotenv = "0.15.0"
reqwest = { version = "0.12.4", features = ["blocking"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
