[package]
name = "ex_48_grabbing_the_weather"
version = "0.1.0"
edition = "2021"

[dependencies]
akshually = "0.2.3"
reqwest = { version = "0.12.4", features = ["blocking"] }
serde = { version = "1.0.203", features = ["derive"] }
serde_json = "1.0.117"
