[package]
name = "ex_27_validating_inputs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
akshually = "0.2.3"
regex = "1.10.4"
